#!/usr/bin/env python
import argparse
import rich.traceback
rich.traceback.install()

import solve, post

# Command line arguments
parser = argparse.ArgumentParser(description=
        'A Python CFD solver based on the FIVER algorithm.')
parser.add_argument('mode', default='all', nargs='?',
        help="Mode of operation. Options are 'solve', 'post', and "
        "'all'. (Default: 'all')")
parser.add_argument('--sum', dest='accumulate',
        help=
        'placeholder')
args = parser.parse_args()

# Run solver
if args.mode == 'solve' or args.mode == 'all':
    print('Checking for breakpoints...', end='', flush=True)
    show_progress_bar = True
    files = ['solve.py', 'residual.py']
    # Check to see if the code contains any breakpoints
    for fname in files:
        with open(fname) as f:
            if 'breakpoint()' in f.read():
                # If so, turn off the progress bar - it conflicts with Pdb
                show_progress_bar = False
                break
    print('done')
    solve.main(show_progress_bar)

# Run post processing
if args.mode == 'post' or args.mode == 'all':
    post.post_process()
