#!/usr/bin/env python
import argparse

import main

# Command line arguments
parser = argparse.ArgumentParser(description=
        'A Python CFD solver based on the FIVER algorithm.')
parser.add_argument('mode', default='all', nargs='?',
        help="Mode of operation. Options are 'solve', 'post', and "
        "'all'. (Default: 'all')")
parser.add_argument('--sum', dest='accumulate',
        help=
        'placeholder')
args = parser.parse_args()

# Run solver
if args.mode == 'solve' or args.mode == 'all':
    main.main()
